import Head from 'next/head'
import { Inter } from '@next/font/google'
import MainMenu from '../components/mainmenu/MainMenu'
import Title from '../components/title/Title'
import About from '../components/about/About'
import Programm from '../components/programm/Programm'
import Steps from '../components/steps/Steps'
import Gap from '../components/commons/gap/Gap'
import Faq from '../components/faq/Faq'
import Review from '../components/review/Rreview'
import Gallery from '../components/gallery/Gallery'
import Contact from '../components/contact/Contact'
import Footer from '../components/footer/Footer'




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const style={
    "width":"1224px",
    "margin":"0 auto",
  }
  return (
    <>
      <Head>
        <title>WEBTRONICS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        
    <div style={style}>
      <MainMenu/>
      <Title/>
      <Gap/>
      <main>
      <About/>
      <Gap/>
      <Programm/>
      <Gap/>
      <Steps/>
      <Gap/>
      <Faq/>
      <Gap/>
      <Review/>
      <Gap/>
      <Gallery/>
      <Gap/>
      <Contact/>
      <Gap/>
      </main>
    </div>
    <Footer />

        
      
      
    </>
  )
}
